sat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),  
    path('login/', include('login.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('home.urls')),
    path('perfil/', include('perfil.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('tareas/', include('tareas.urls')),
    path('categorias/', include('categorias.urls')),
    path('estadisticas/', include('estadisticas.urls')),
    path('comentarios/', include('comentarios.urls')),
    path('calificaciones/', include('calificaciones.urls')),
    # path('', include('example.urls')),
]


# Para hacer funcionar los archivos media en la subida de imagenes
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tareas/urls.py
from django.urls import path
from tareas.views import (ListadoTareas,
CrearTarea,
EliminarTarea,
EditarTarea,
CalificarTarea,
ListadoArchivoTareas)

urlpatterns = [

    path('lista_tareas/', ListadoTareas.as_view(), name='lista_tareas'),
    path('agg_tareas/', CrearTarea.as_view(), name='agg_tareas'),
    path('eliminar_tareas/<int:pk>', EliminarTarea, name='eliminar_tareas'),
    path('editar_tareas/<int:pk>', EditarTarea, name='editar_tareas'),
    path('calificar_tarea/', CalificarTarea.as_view(), name='calificar_tarea'),
    path('lista_archivo/', ListadoArchivoTareas.as_view(), name='lista_archivo'),


    # path('usuarios/', views.ListadoUsuarios.as_view(), name='usuarios'),
]

tareas/models.py
from django.db import models
from categorias.models import Categorias
from django.contrib.auth.models import User

class Status(models.Model):
    status = models.CharField(max_length=150,verbose_name='status')

    def __str__(self):
        return self.status

    class Meta:
        verbose_name = 'Status'
        verbose_name_plural = 'Status'
        ordering = ['-id']  

class Prioridad(models.Model):
    prioridad = models.CharField(max_length=150,verbose_name='prioridad')

    def __str__(self):
        return self.prioridad

    class Meta:
        verbose_name = 'Prioridad'
        verbose_name_plural = 'Prioridades'
        ordering = ['-id']  

class Tareas(models.Model):

    tarea =  models.CharField(max_length=150,verbose_name='tarea')
    descripcion =  models.CharField(max_length=200,verbose_name='descripcion')
    status = models.ForeignKey(Status, on_delete=models.CASCADE,related_name='status_tarea')
    prioridad = models.ForeignKey(Prioridad, on_delete=models.CASCADE,related_name='prioridad_tarea')
    categoria = models.ForeignKey(Categorias,on_delete=models.CASCADE, related_name='categorias_tarea')
    porcentaje = models.IntegerField(default=0)
    CreadaPor = models.ForeignKey(User,on_delete=models.CASCADE,related_name = 'creador_tarea')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name = 'asignaciones')
    Fcreacion = models.DateField(auto_now_add=True)
    Ffinal = models.DateField(help_text='fecha plazo')
    Fterminada = models.DateField(help_text='fecha final', null=True,blank=True)

    def __str__(self):
        return self.tarea

    class Meta:
        verbose_name = 'Tarea'
        verbose_name_plural = 'Tareas'
        ordering = ['-id']  



class ArchivoTareas(models.Model):

    tarea =  models.CharField(max_length=150,verbose_name='archivo')
    descripcion =  models.CharField(max_length=200,verbose_name='descripcion')
    status = models.ForeignKey(Status, on_delete=models.CASCADE,related_name='status_archivo')
    prioridad = models.ForeignKey(Prioridad, on_delete=models.CASCADE,related_name='prioridad_archivo')
    categoria = models.ForeignKey(Categorias,on_delete=models.CASCADE, related_name='categorias_archivo')
    porcentaje = models.IntegerField(default=0)
    CreadaPor = models.ForeignKey(User,on_delete=models.CASCADE,related_name = 'creador_archivo')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name = 'user_archivo')
    Fcreacion = models.DateTimeField(auto_now_add=True)
    Ffinal = models.DateField(help_text='fecha plazo')
    Fterminada = models.DateField(help_text='fecha final', null=True,blank=True)
    calificacion = models.IntegerField(help_text='Calificación del la tarea', null=True,blank=True)

    def __str__(self):
        return self.tarea

    class Meta:
        verbose_name = 'ArchivoTarea'
        verbose_name_plural = 'ArchivoTareas'
        ordering = ['-id']

tareas/forms.py
from django import forms
from .models import Tareas
from .models import Status
from django.db.models import Q
from django.contrib.auth.models import User




class TareasForm(forms.ModelForm):

    class Meta:
        model = Tareas
        fields =  '__all__'
        exclude = ['Fterminada']


    status = forms.ModelChoiceField(label="Status",queryset= Status.objects.all(),required = True,widget=forms.Select(attrs={'class': 'form-control'}))
    Ffinal = forms.DateField(label="Fecha Final",widget=forms.DateInput(attrs={'class': 'form-control','placeholder' : '20/5/2023'}))
    CreadaPor = forms.ModelChoiceField(label=False,queryset=User.objects.all(),disabled = True, required = False,widget=forms.Select(attrs={'class': 'form-control','hidden' : True}))
    user = forms.ModelChoiceField(label="Asignar",queryset=User.objects.all())



    # tarea = forms.CharField(required=True, widget=forms.TextInput())
    # descripcion = forms.CharField(required=True, widget=forms.TextInput())
    # categoria_id = forms.ModelChoiceField(label='categoria',queryset=Categorias.objects.all())
    # prioridad_id = forms.ModelChoiceField(label='prioridad',queryset=Prioridad.objects.all())
    # status_id = forms.ModelChoiceField(label='status', queryset=Status.objects.all())
    # porcentaje = forms.IntegerField(widget=forms.NumberInput())
    # Asignada_id = forms.ModelChoiceField(label="Asignar",queryset=User.objects.all())
    # CreadaPor_id = forms.ModelChoiceField(label="Creada por",queryset=User.objects.all())
    # Ffinal = forms.DateField(label="Fecha Final")

class TareasForm2(forms.ModelForm):

    class Meta:
        model = Tareas
        fields =  '__all__'
        exclude = ['Fterminada']


    status = forms.ModelChoiceField(label="Status",queryset= Status.objects.all().exclude(status = 'Re_abierta').exclude(status = 'Revisión').exclude(status='Finalizada'),required = False,widget=forms.Select(attrs={'class': 'form-control'}))
    Ffinal = forms.DateField(label="Fecha Final",widget=forms.DateInput(attrs={'class': 'form-control','placeholder' : '20/5/2023'}))
    CreadaPor = forms.ModelChoiceField(label=False,queryset=User.objects.all(),disabled = True, required = False,widget=forms.Select(attrs={'class': 'form-control','hidden' : True}))
    user = forms.ModelChoiceField(label=False,queryset=User.objects.all(),disabled = True, required = False,widget=forms.Select(attrs={'class': 'form-control','hidden' : True}))

tareas/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from datetime import datetime

from tareas.models import Tareas,Status,Prioridad, ArchivoTareas
from categorias.models import Categorias
from django.contrib.auth.models import User

from django.views.generic import TemplateView,ListView, CreateView, UpdateView, DeleteView, View

from tareas.forms import TareasForm
from tareas.forms import TareasForm2


# Create your views here.


class ListadoTareas(ListView):
    model = Tareas
    template_name = 'lista_tareas.html'
    context_object_name = 'tareas'             # permite cambiar de nombre al objetos listview que se llamara en la vista
    queryset=  Tareas.objects.all()           #  Permite realizar filtros a la consulta
                                              # PROBAR:REMPLAZAR QUERYSET por su metodo de este modo:
                                                ## def get_queryset(self):
                                                ##  return self.model.objects.filter(fitrodecampo)   
                                                
    @method_decorator(login_required)             #Puede agrupar decoradores
    def dispatch(self, request, *args, **kwargs):
        # if not request.user.has_perm('productos.view_productos'):
        #       messages.success(request,"ACCESO DENEGADO")
        #       return redirect('home')
        #print(Perfil.objects.select_related('user').query)
        #print(User.objects.prefetch_related('username').query)
        # print(Tareas.objects.all().values('categorias__categoria'))

        return super( ListadoTareas,self).dispatch(request, *args, **kwargs)


class ListadoArchivoTareas(ListView):
    '''
    List Vire que devuelve la lista de las tareas archivadas en la tabla de archivo muerto
    '''
    model = ArchivoTareas
    template_name = 'lista_archivo.html'
    context_object_name = 'archivo'   
    queryset=  ArchivoTareas.objects.all() 
                                                
    @method_decorator(login_required)         
    def dispatch(self, request, *args, **kwargs):
        return super( ListadoArchivoTareas,self).dispatch(request, *args, **kwargs)



class CrearTarea(View):
    
    template_name = 'agg_tarea.html'
    Model = Tareas
    autorizacion = 0

    def get(self,request):
        # form = TareasForm()

        rol = request.user.groups.all().values('name')
        verifica = Autorizacion(rol)

        
        print(verifica)
        if verifica == 1:
            form = TareasForm()
            return render(request,self.template_name,{"form":form})
        if verifica == 2:
            form = TareasForm()
            return render(request,self.template_name,{"form":form})    
        if verifica == 3:
            form = TareasForm2()
            return render(request,self.template_name,{"form":form})
        else:
            return redirect('lista_tareas')
        
        

    def post(self,request):
        
        rol = request.user.groups.all().values('name')
        verifica = Autorizacion(rol) 
        
        if verifica == 1:
            form = TareasForm(request.POST)

            
            if form.is_valid():
                # form.save()
                
                post = form.save(commit = False)
                post.CreadaPor_id = request.user.id
                
                if post.porcentaje > 100 :
                    post.porcentaje = 100
                else:
                    post.porcentaje = 0
                
                
                # if not post.status_id:                            # Creacion del status inicial por default
                    
                #     post.status_id = 1                           


                post.save()

                #  Logica para guardar un Form.form
                # if form.is_valid():
                #     campo = form.cleaned_data['nombredelcampo']
                #     Tabla.objects.create(campo =  campo )

                messages.success(request,"Tarea Creada")
                return redirect('lista_tareas')
            else:
            
                # for msg in form.error_messages:
                #     messages.error(request, form.error_messages[msg])

                return render(request,self.template_name,{"form":form})
        
        if verifica == 2:
            form = TareasForm(request.POST)

            
            if form.is_valid():
                # form.save()
                
                post = form.save(commit = False)
                post.CreadaPor_id = request.user.id
                
                if post.porcentaje > 100 :
                    post.porcentaje = 100
                else:
                    post.porcentaje = 0

                if not post.status_id:                            # Creacion del status inicial por default
                    
                    post.status_id = 1                           


                post.save()

                #  Logica para guardar un Form.form
                # if form.is_valid():
                #     campo = form.cleaned_data['nombredelcampo']
                #     Tabla.objects.create(campo =  campo )

                messages.success(request,"Tarea Creada")
                return redirect('lista_tareas')
            else:
            
                # for msg in form.error_messages:
                #     messages.error(request, form.error_messages[msg])

                return render(request,self.template_name,{"form":form})
                   
        if verifica == 3:
            form = TareasForm2(request.POST)

            
            if form.is_valid():
                # form.save()
                
                post = form.save(commit = False)
                post.CreadaPor_id = request.user.id
                post.user_id = request.user.id
                if post.porcentaje > 100 :
                    post.porcentaje = 100
                else:
                    post.porcentaje = 0

                if not post.status_id:                            # Creacion del status inicial por default
                    
                    post.status_id = 1                           


                post.save()

                #  Logica para guardar un Form.form
                # if form.is_valid():
                #     campo = form.cleaned_data['nombredelcampo']
                #     Tabla.objects.create(campo =  campo )

                messages.success(request,"Tarea Creada")
                return redirect('lista_tareas')
            else:
            
                # for msg in form.error_messages:
                #     messages.error(request, form.error_messages[msg])

                return render(request,self.template_name,{"form":form})
        else:
            return redirect('lista_tareas')    
              
        
        
        # form = TareasForm(request.POST)

        
        # if form.is_valid():
        #     # form.save()
            
        #     post = form.save(commit = False)
        #     post.CreadaPor_id = request.user.id
            
        #     if post.porcentaje > 100 :
        #         post.porcentaje = 100
        #     else:
        #         post.porcentaje = 0

        #     post.save()

        #     #  Logica para guardar un Form.form
        #     # if form.is_valid():
        #     #     campo = form.cleaned_data['nombredelcampo']
        #     #     Tabla.objects.create(campo =  campo )

        #     messages.success(request,"Tarea Creada")
        #     return redirect('lista_tareas')
        # else:
        
        #     # for msg in form.error_messages:
        #     #     messages.error(request, form.error_messages[msg])
            
        #     return render(request,self.template_name,{"form":form})
    



def EliminarTarea(request, pk):
    tarea = get_object_or_404(Tareas, id = pk)
    rol = request.user.groups.all().values('name')
    verifica = Autorizacion(rol)
    verifica_tarea = Tarea_Autorizacion(pk)
    

    if verifica == 1:
        tarea.delete()
        messages.success(request,"Tarea eliminada")
        return redirect('lista_tareas')
    if verifica == 2: 
        if verifica_tarea == 1:
            messages.error(request,"No esta Autorizado para realizar esta acción!") 
            return redirect('lista_tareas')
        if verifica_tarea == 2 and tarea.CreadaPor == request.user:    
            messages.success(request,"Tarea eliminada")
            return redirect('lista_tareas')
        elif verifica_tarea == 3:
            tarea.delete()
            messages.success(request,"Tarea eliminada")
            return redirect('lista_tareas')
        else:
            messages.error(request,"No esta Autorizado para realizar esta acción!")    
            return redirect('lista_tareas')
    else:
        messages.error(request,"No esta Autorizado para realizar esta acción!")
        return redirect('lista_tareas')


@login_required
def EditarTarea(request, pk):
    
    tarea = get_object_or_404(Tareas,id = pk)                                       # obtencion del objeto
    
    rol = request.user.groups.all().values('name')                                  #3 Verificaion del Rol
    verifica = Autorizacion(rol)
    verifica_tarea = Tarea_Autorizacion(pk)

    if verifica == 1 or verifica == 2 or tarea.user == request.user:                   # Verificaion del rol o del usuario asignado
        
        if verifica == 1 or verifica == 2:                                             # Condicional que control el form que pinta el get
            data = {
                    'form': TareasForm(instance=tarea)
                }
        else:
            data = {
                    'form': TareasForm2(instance=tarea)
                } 

tareas/templates/agg_tarea.html
{% extends "home.html"%}
{% load static %}
{% load crispy_forms_tags %}


{% block link %}
        
{% endblock%}

{% block title %} Crear Tarea {% endblock %}

{% block content %}
    
    <h3>Agregar Tarea</h3>

    <br>
        <div class="row">

            
            <div class="col-12 col-md-7 offset-md-3">

                <div class="card">

                    <div class="card-body">

                        <form action="" method="post">
                            {% csrf_token %}
                
                        
                            {{ form|crispy }}
                            <div class="text-center">
                                <input class="btn btn-success" type="submit" value="Agregar">
                                &ensp;
                                <a href="{% url 'lista_tareas' %} " class="btn btn-danger">Cancelar</a>
                            </div>
                
                        </form>
    
                    </div>


                </div>
 
            </div>

        </div>


        <br>
        


  

   
{% endblock %}

tareas/templates/editar_tarea.html
{% extends "home.html"%}
{% load static %}
{% load crispy_forms_tags %}


{% block link %}
        
{% endblock%}

{% block title %} Editar Tarea {% endblock %}

{% block content %}
    
    <h3>Editar Tarea</h3>

    <br>
        <div class="row">

            
            <div class="col-12 col-md-7 offset-md-3">

                <div class="card">

                    <div class="card-body">

                        <form action="" method="post">
                            {% csrf_token %}
                
                        
                            {{ form|crispy }}
                            <div class="text-center">
                                <input class="btn btn-success" type="submit" value="Actualizar">
                                &ensp;
                                <a href="{% url 'lista_tareas' %} " class="btn btn-danger">Cancelar</a>
                            </div>
                
                        </form>
    
                    </div>


                </div>
 
            </div>

        </div>


        <br>
        


  

   
{% endblock %}

tareas/templates/lista_tareas.html
{% extends "home.html"%}
{% load static %}


{% block link %}
        
{% endblock%}

{% block title %} Tareas {% endblock %}


{% block content %}
    
    <h3>Tareas</h3>

    <a href="{% url 'agg_tareas' %}" class="btn btn-success main-add-button" title="Agregar"> <i class="fa fa-plus"></i></a>


        {% if tareas %}
            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Lista de Tareas</h6>
                
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Tarea</th>
                                    <th>Descripción</th>
                                    <th>Categoría</th>
                                    <th>Prioridad</th>
                                    <th>Status</th>
                                    <th>Asignada</th>
                                    <th>Creada</th>
                                    <th>Porcentaje</th>
                                    <th>Creación</th>
                                    <th>Plazo</th>
                                    <th style="width:9%">Acción</th>
                                </tr>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Tarea</th>
                                    <th>Descripción</th>
                                    <th>Categoría</th>
                                    <th>Prioridad</th>
                                    <th>Status</th>
                                    <th>Asignada</th>
                                    <th>Creada</th>
                                    <th>Porcentaje</th>
                                    <th>Creación</th>
                                    <th>Plazo</th>
                                    <th>Acción</th>
                                </tr>
                            </tfoot>
                            <tbody>
                                {% for tarea in tareas %}
                                    <tr>
                                        <td>{{ tarea.id}}</td>
                                        <td>{{ tarea.tarea}}</td>
                                        <td>{{ tarea.descripcion}}</td>
                                        <td>{{ tarea.categoria}}</td>
                                        <td>{{ tarea.prioridad.prioridad}}</td>
                                        <td>{{ tarea.status.status}}</td>
                                        <td>{{ tarea.user.username}}</td>
                                        <td>{{ tarea.CreadaPor.username}}</td>
                                        <td>{{ tarea.porcentaje}}</td>
                                        <td>{{ tarea.Fcreacion}}</td>
                                        <td>{{ tarea.Ffinal}}</td>
                                        <td>
                                            <div class="text-center">
                                                <a href="{% url 'editar_tareas' tarea.id%}" 
                                                title="Editar" 
                                                class="btn btn-info btn-sm">                                              
                                                    <i class="fa fa-edit"></i></a>
                                                {% if perms.tareas.delete_tareas%}
                                                    <a href="{% url 'eliminar_tareas' tarea.id%}" 
                                                title="Eliminar" 
                                                class="btn btn-danger btn-sm">                                               
                                                    <i class="fa fa-trash"></i></a>
                                                {% endif %}    
                                                <a href="{% url 'lista_comentarios' tarea.id %}" 
                                                title="Comentar" 
                                                class="btn btn-info btn-sm">
                                                    <i class="fa fa-comment"></i></a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}                       
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            {% else %}
                <br>
                <div class="text-center">
                    <b>No se encontraron Tareas</b>
                </div>

        {% endif %}    

        
            
    {% block js %}
        {% if messages %}
            {% for m in messages %}
                <script>
                    Swal.fire({
                        "title":"Operación realizada!",
                        "text": "{{m}}",
                        "icon":"success"
                    });
                </script>
            {% endfor %}
        {% endif %}    


        {% if archived %}
            <!-- Modal -->
            <div
            id="exampleModal"  
            class="modal fade bd-example-modal-lg" 
            tabindex="-1" 
            role="dialog" 
            aria-labelledby="myLargeModalLabel" 
            aria-hidden="true"
            data-backdrop="static">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">

                        <div class="modal-header">
                            <h5 class="modal-title">La tarea ha sido finalizada con éxito</h5>
                            <!--button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button-->
                            </div>
                            <div class="modal-body" data-task="{{archived}}">
                            <h3 class="starrating_title">¡Califica la tarea!</h3>

                            <form method="post" action="{% url 'calificar_tarea' %}">
                                {% csrf_token %}

                                <div class="starrating risingstar d-flex justify-content-center flex-row-reverse">
                                    <input type="radio" id="star5" name="rating" value="5" /><label for="star5" title="5 star">
                                        <i class="fa fa-star" ></i>
                                    </label>
                                    <input type="radio" id="star4" name="rating" value="4" />
                                    <label for="star4" title="4 star">
                                        <i class="fa fa-star" ></i>
                                    </label>
                                    <input type="radio" id="star3" name="rating" value="3" />
                                    <label for="star3" title="3 star">
                                        <i class="fa fa-star" ></i>
                                    </label>
                                    <input type="radio" id="star2" name="rating" value="2" />
                                    <label for="star2" title="2 star">
                                        <i class="fa fa-star" ></i>
                                    </label>
                                    <input type="radio" id="star1" name="rating" value="1" />
                                    <label for="star1" title="1 star">
                                        <i class="fa fa-star" ></i>
                                    </label>
                                </div>
                                <input type="hidden" name="task" value="{{archived}}">
                                <div class="modal-footer">
                                    <button id="btnCalificar" disabled="disabled" type="submit" class="btn btn-primary">Calificar</button>
                                  </div>
                            </form>
                    </div>
                </div>
                </div>

            <script>
                $(window).on('load', function() {
                $('#exampleModal').modal('show');
                });


                $('input[name="rating"]').on('click', function() {
                    $('#btnCalificar').prop('disabled', false);
                });
            </script>
        {% endif %}          

      
    {% endblock%}


{% endblock %}